#!/bin/sh
# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev

# use the /dev/console device node from devtmpfs if possible to not
# confuse glibc's ttyname_r().
# This may fail (E.G. booted with console=), and errors from exec will
# terminate the shell, so use a subshell for the test
if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi

# Mount our paths
# Mount files from iso
mkdir /mnt/iso_files
mount -t iso9660 -o ro /dev/sr0 /mnt/iso_files
# Mount progs
mkdir /progs
mount /mnt/iso_files/progs /progs
# Mount additional files
mkdir /files
mount /mnt/iso_files/files /files

export PATH=$PATH:/progs

exec /sbin/init "$@"
